apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-ebs-redis-pvc
  namespace: docker-registry
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-gp2
  resources: 
    requests:
      storage: 1Gi