apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-gp2
  namespace: docker-registry
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fstype: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate